name: Test workflow for terraform
on:
  push:
    branches: ["master"]
jobs:
  Deploy:
    name: Terraform deployment
    runs-on: ubuntu-latest
    env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          REGION: ${{ secrets.REGION }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - name: Configuring environment variables
        run: export AWS_ACCESS_KEY="${AWS_ACCESS_KEY}"
      - name: Configuring environment variables
        run: export AWS_SECRET_KEY="${AWS_SECRET_KEY}"
      - name: Configuring environment variables
        run: export REGION="${REGION}"
        
      - name: Terraform format check
        run: terraform fmt
      - name: Initialize terraform configuration directory
        run: terraform init
      - name: Validate the configuration
        run: terraform validate
      - name: Plan the changes
        run: terraform plan
      - name: Apply the changes
        run: terraform apply